# Generated by Django 4.2 on 2024-11-11 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200, verbose_name='Название поста')),
                ('photos', models.ImageField(upload_to='blog_photos/', verbose_name='Фото')),
                ('contents', models.TextField(verbose_name='Содержание поста')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='Теги')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Пост KYOTOCHAI',
                'verbose_name_plural': 'Посты KYOTOCHAI',
                'ordering': ['titles', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('events_date', models.DateField(verbose_name='Дата мероприятия')),
                ('events_time', models.TimeField(verbose_name='Время мероприятия')),
                ('events_type', models.CharField(max_length=120, verbose_name='Тип мероприятия')),
                ('descriptions', models.TextField(verbose_name='Описание мероприятия')),
                ('attendeess_count', models.PositiveIntegerField(default=0, verbose_name='Количество присутствующих')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
                ('attendeess', models.ManyToManyField(blank=True, related_name='events_attendees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятие KYOTOCHAI',
                'verbose_name_plural': 'Мероприятия KYOTOCHAI',
            },
        ),
    ]
